spring.application.name=jogos
spring.datasource.url=jdbc:postgresql://localhost:5432/coringas
spring.datasource.username=postgres
spring.datasource.password=kratos
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
