spring.application.name=exchange

spring.datasource.url=jdbc:postgresql://localhost:5432/exchange
spring.datasource.username=postgress
spring.datasource.password=kratos
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update